name: url-to-markdown
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - pydantic==2.5.0
    - python-multipart==0.0.6
    - requests==2.31.0
    - beautifulsoup4==4.12.2
    - html2text==2020.1.16
    - lxml==4.9.3
    - pydantic-settings==2.1.0
    - selenium==4.15.2
