name: url-to-markdown
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi>=0.104.1,<0.105.0
    - uvicorn[standard]>=0.24.0,<0.25.0
    - pydantic>=2.5.0,<2.6.0
    - python-multipart>=0.0.6,<0.1.0
    - requests>=2.31.0,<2.32.0
    - beautifulsoup4>=4.12.2,<4.13.0
    - lxml>=4.9.3,<4.10.0
    - pydantic-settings>=2.1.0,<2.2.0
    - selenium>=4.15.2,<4.16.0
    - webdriver-manager>=4.0.1,<4.1.0
